version: 4.0.0.{build}

configuration: Release

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

before_build:
- nuget restore

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac
  artifact: MyGet
